# Generated by Django 6.0.7 on 2026-08-15 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='file',
            new_name='files_user_id_99e8c2_idx',
            old_name='storage_fil_user_id_5ec44f_idx',
        ),
    ]
